### ISSUE TITLE
Bold360AI SDK is missing complete nullability annotations

### ISSUE THREAD

**Issue by daniel-beard** [bold360ai/bold360-mobile-samples-ios#21]
Apologies for filing this on the samples repository, but I'm seeing the following with the 360ai SDK:

<img width="279" alt="Screen Shot 2020-07-28 at 3 42 51 PM" src="https://user-images.githubusercontent.com/2645146/88729536-02229680-d0e9-11ea-8b9d-16fb0f227b08.png">

There are many missing nullability annotations and this is preventing us from adding the SDK to our app. Please let me know the right communication channel to get this fixed, it's an absolute blocker for us.

**Comment by ElizaSapir** [comment]
Hey @daniel-beard , it was handled please update to latest version.

**Comment by daniel-beard** [comment]
@ElizaSapir the 3.8.12 cocoapod has an invalid CFShortBundlerVersionString, meaning that anyone that includes that version in their builds can't upload to the appstore
