### ISSUE TITLE
Bold360AI doesn't compile in xcode 11

### ISSUE THREAD

**Issue by jalopezcar** [bold360ai/bold360-mobile-samples-ios#24]
I created an empty project with only the `Bold360AI` pod

https://github.com/jalopezcar/boldchat_test

and when I try to compile with Xcode 11 it doesn't work:

```

...Pods/Target Support Files/Pods-boldchat_test/Pods-boldchat_test-frameworks.sh: line 144: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code
```

I tested with 11.5 or 11.7

I suppose it's related to the EXCLUDED_ARCHS added in the podspec.

It works with Xcode 12

**Comment by ElizaSapir** [comment]
fixed
